"""``DecisionsFeed`` component view-model (task 13.1, Req 14.1, 14.2, 14.5, 14.7, 14.8).

The dashboard's "Decisions to make" feed lists every *open* Decision generated by
Practice_Intelligence with an approve and a dismiss control on each, shows an
empty-state message when there are none, and updates in real time as Decisions
are added or resolved. This module is the **pure Python view-model** for that
feed: it takes the Decisions the BFF read through ``DecisionStore.list_open``
(see :meth:`clinic_front_desk.dashboard.bff.DashboardBFF.open_decisions`) and
shapes them into a render-ready :class:`DecisionsFeedView` the HTML partial and
JS snippet render. It contains no I/O, no store access, and no timing logic, so
it is trivially unit-testable; the real-time transport and optimistic UI live in
``dashboard/web/decisions_feed.{html,js}``.

Ordering (Req 14.1)
-------------------
The feed is ordered most-recently-generated first. ``DecisionStore.list_open``
already returns that order, but the view-model re-establishes it defensively by
sorting on ``generated_at`` descending with a stable tiebreak, so the rendered
order is correct regardless of the order the caller supplies.

Controls (Req 14.2)
-------------------
Every card carries an :class:`ControlView` for *approve* and one for *dismiss*,
each naming the action and the target ``decision_id``. The JS binds these to the
``DecisionActionService.approve`` / ``.dismiss`` calls on the BFF.

Empty state (Req 14.7)
----------------------
When no open Decision exists, :attr:`DecisionsFeedView.is_empty` is ``True`` and
:attr:`DecisionsFeedView.empty_state_message` carries the "nothing to review"
copy the client renders in place of the card list.

Real-time add & optimistic removal (Req 14.5, 14.8)
---------------------------------------------------
These are client behaviours driven by the change-event channel; the view-model
supports them by giving each card a stable ``id`` used as its reconciliation key.
The documented contract the JS implements:

- **Add (Req 14.8):** on a ``ChangeEvent{entity=decision, kind=created}`` the
  client re-reads :meth:`DashboardBFF.open_decisions`, rebuilds the feed via
  :func:`build_decisions_feed`, and inserts the new card in newest-first order —
  well inside the ≤ 5 s budget because the channel fan-out is synchronous.
- **Optimistic removal (Req 14.5):** on approve/dismiss the client removes the
  card immediately (optimistically) and then *reconciles* against the confirming
  ``ChangeEvent{entity=decision, kind=updated}`` (the store emits this when
  ``set_status`` resolves the Decision). If the action fails (``ACTION_FAILED``,
  Req 14.6) no confirming event arrives and the client restores the card with an
  error indication. Reconciliation is by card ``id``.
"""

from __future__ import annotations

import html
import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

from clinic_front_desk.models import (
    Decision,
    DecisionKind,
    StoreResult,
    is_err,
)

# Directory holding the HTML partials this module renders (sibling ``web/``).
_WEB_DIR = Path(__file__).resolve().parent.parent / "web"

#: Default endpoint the client JS re-fetches the rebuilt feed from. Callers may
#: override when a deployment mounts the dashboard under a different path.
DEFAULT_DECISIONS_ENDPOINT = "/dashboard/decisions"

#: Empty-state copy shown when there are no open Decisions (Req 14.7).
EMPTY_STATE_MESSAGE = "No decisions to review right now."

#: Copy shown when the open-decisions read itself failed, so the feed renders a
#: recoverable error rather than a misleading empty state.
LOAD_ERROR_MESSAGE = "Decisions could not be loaded. Please retry."

#: Human-readable labels for each Decision kind, used as a card's headline tag.
_KIND_LABELS: dict[DecisionKind, str] = {
    DecisionKind.GAP_FILL: "Fill schedule gap",
    DecisionKind.NO_SHOW_TREND: "No-show trend",
    DecisionKind.SCHEDULE_GAP: "Schedule gap",
    DecisionKind.UNMET_DEMAND: "Unmet demand",
    DecisionKind.UNOFFERED_SERVICE_DEMAND: "Demand for an unoffered service",
}


def _kind_label(kind: DecisionKind) -> str:
    """Return the display label for a Decision kind (falls back to the value)."""
    return _KIND_LABELS.get(kind, str(kind))


@lru_cache(maxsize=None)
def _load_template(name: str) -> str:
    """Read and cache an HTML partial from the ``web/`` directory."""
    return (_WEB_DIR / name).read_text(encoding="utf-8")


@dataclass(frozen=True)
class ControlView:
    """A render-ready approve/dismiss control for one Decision (Req 14.2).

    Attributes:
        label: The button text the client renders.
        action: The action the control triggers, ``"approve"`` or ``"dismiss"``.
        decision_id: The Decision the control acts on; the JS passes this to
            ``DecisionActionService.approve``/``.dismiss``.
    """

    label: str
    action: str
    decision_id: str


@dataclass(frozen=True)
class DecisionCardView:
    """One open Decision shaped for rendering in the feed (Req 14.1, 14.2).

    Attributes:
        id: The Decision id; the stable reconciliation key for real-time
            add/removal (Req 14.5, 14.8).
        kind: The raw Decision kind value.
        kind_label: Human-readable label for ``kind``.
        summary: The finding summary line.
        recommended_action: The action the doctor is being asked to approve.
        supporting_record_count: How many records support the finding (≥ 5).
        generated_at: ISO-8601 UTC timestamp the Decision was generated.
        approve: The approve control (Req 14.2).
        dismiss: The dismiss control (Req 14.2).
    """

    id: str
    kind: str
    kind_label: str
    summary: str
    recommended_action: str
    supporting_record_count: int
    generated_at: str
    approve: ControlView
    dismiss: ControlView


@dataclass(frozen=True)
class DecisionsFeedView:
    """The whole "Decisions to make" feed, ready to render.

    Attributes:
        cards: Open Decisions, newest-first (Req 14.1). Empty when there are
            none or when the read failed.
        is_empty: ``True`` when there are no cards to show (Req 14.7).
        empty_state_message: The message to render when ``is_empty`` is ``True``.
        has_error: ``True`` when the open-decisions read failed; the client
            should render :attr:`empty_state_message` as a recoverable error.
    """

    cards: list[DecisionCardView] = field(default_factory=list)
    is_empty: bool = True
    empty_state_message: str = EMPTY_STATE_MESSAGE
    has_error: bool = False


def _card(decision: Decision) -> DecisionCardView:
    """Shape a single :class:`Decision` into a :class:`DecisionCardView`."""
    return DecisionCardView(
        id=decision.id,
        kind=str(decision.kind),
        kind_label=_kind_label(decision.kind),
        summary=decision.summary,
        recommended_action=decision.recommended_action,
        supporting_record_count=decision.supporting_record_count,
        generated_at=decision.generated_at,
        approve=ControlView(
            label="Approve", action="approve", decision_id=decision.id
        ),
        dismiss=ControlView(
            label="Dismiss", action="dismiss", decision_id=decision.id
        ),
    )


def build_decisions_feed(decisions: list[Decision]) -> DecisionsFeedView:
    """Build the feed view-model from open Decisions (Req 14.1, 14.2, 14.7).

    Orders the Decisions most-recently-generated first (Req 14.1) — sorting
    defensively on ``generated_at`` descending with a stable tiebreak so the
    result is correct regardless of the caller's order — attaches approve/dismiss
    controls to each (Req 14.2), and yields an empty view carrying the
    empty-state message when the list is empty (Req 14.7).

    Args:
        decisions: The open Decisions (typically from ``open_decisions()``).

    Returns:
        A :class:`DecisionsFeedView` ready for the HTML partial to render.
    """
    ordered = sorted(decisions, key=lambda d: d.generated_at, reverse=True)
    cards = [_card(d) for d in ordered]
    return DecisionsFeedView(
        cards=cards,
        is_empty=not cards,
        empty_state_message=EMPTY_STATE_MESSAGE,
        has_error=False,
    )


def build_decisions_feed_from_result(
    result: StoreResult[list[Decision]],
) -> DecisionsFeedView:
    """Build the feed from the BFF's ``open_decisions()`` result.

    Wraps :func:`build_decisions_feed` and maps a read failure to an error view
    (``has_error=True``) so the client renders a recoverable error instead of a
    misleading "no decisions" empty state.

    Args:
        result: The :class:`StoreResult` from ``DashboardBFF.open_decisions``.

    Returns:
        The feed view-model, or an error view when the read failed.
    """
    if is_err(result):
        return DecisionsFeedView(
            cards=[],
            is_empty=True,
            empty_state_message=LOAD_ERROR_MESSAGE,
            has_error=True,
        )
    return build_decisions_feed(result.value)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _render_card(card: DecisionCardView) -> str:
    """Render one Decision ``<li>`` with all interpolated text escaped (Req 14.2).

    Mirrors the ``<template>`` in ``web/decisions_feed.html`` so a JS-disabled
    client still sees the same card, and carries ``data-decision-id`` — the
    reconciliation key the JS uses for optimistic removal / real-time add
    (Req 14.5, 14.8). Patient/finding-derived text is HTML-escaped so it cannot
    inject markup.
    """
    return (
        '<li class="decision-card" '
        f'data-decision-id="{html.escape(card.id, quote=True)}" '
        f'data-kind="{html.escape(card.kind, quote=True)}">'
        f'<p class="decision-card__kind" data-field="kind_label">'
        f"{html.escape(card.kind_label)}</p>"
        f'<p class="decision-card__summary" data-field="summary">'
        f"{html.escape(card.summary)}</p>"
        f'<p class="decision-card__action" data-field="recommended_action">'
        f"{html.escape(card.recommended_action)}</p>"
        '<p class="decision-card__support">Supported by '
        f'<span data-field="supporting_record_count">'
        f"{card.supporting_record_count}</span> records</p>"
        '<p class="decision-card__error" data-field="error" role="alert" hidden></p>'
        '<div class="decision-card__controls">'
        f'<button type="button" class="decision-card__approve" '
        f'data-action="{html.escape(card.approve.action, quote=True)}" '
        f'data-decision-id="{html.escape(card.approve.decision_id, quote=True)}">'
        f"{html.escape(card.approve.label)}</button>"
        f'<button type="button" class="decision-card__dismiss" '
        f'data-action="{html.escape(card.dismiss.action, quote=True)}" '
        f'data-decision-id="{html.escape(card.dismiss.decision_id, quote=True)}">'
        f"{html.escape(card.dismiss.label)}</button>"
        "</div>"
        "</li>"
    )


def _card_payload(card: DecisionCardView) -> dict[str, object]:
    """Shape one card for the JSON the JS hydrates from (fields the JS reads)."""
    return {
        "id": card.id,
        "kind": card.kind,
        "kind_label": card.kind_label,
        "summary": card.summary,
        "recommended_action": card.recommended_action,
        "supporting_record_count": card.supporting_record_count,
        "generated_at": card.generated_at,
    }


def _feed_json(view: DecisionsFeedView) -> str:
    """Serialize the view-model as embeddable JSON for JS hydration (Req 14.1).

    ``</`` is escaped so the payload cannot terminate the surrounding
    ``<script>`` element.
    """
    payload = {
        "cards": [_card_payload(card) for card in view.cards],
        "is_empty": view.is_empty,
        "empty_state_message": view.empty_state_message,
        "has_error": view.has_error,
    }
    return json.dumps(payload).replace("</", "<\\/")


def render_decisions_feed(
    feed: DecisionsFeedView | list[Decision],
    *,
    decisions_endpoint: str = DEFAULT_DECISIONS_ENDPOINT,
) -> str:
    """Render the ``DecisionsFeed`` partial to an HTML string (Req 14.1, 14.2, 14.7).

    Builds the view-model (when given a list of Decisions), renders one card per
    open Decision newest-first (Req 14.1) with approve/dismiss controls
    (Req 14.2), toggles the empty-state message when there are none (Req 14.7),
    and embeds the view-model as JSON so the client JS can take over real-time
    add / optimistic removal (Req 14.5, 14.8). All interpolated text is escaped.

    Args:
        feed: A pre-built :class:`DecisionsFeedView` (e.g. an error view from
            :func:`build_decisions_feed_from_result`) or a list of open
            Decisions to shape here.
        decisions_endpoint: Base URL embedded for the client JS to re-fetch the
            rebuilt feed from on a real-time add.

    Returns:
        The rendered HTML partial as a string.
    """
    view = feed if isinstance(feed, DecisionsFeedView) else build_decisions_feed(feed)
    cards_html = "\n    ".join(_render_card(card) for card in view.cards)
    template = _load_template("decisions_feed.html")
    return template.format(
        decisions_endpoint=html.escape(decisions_endpoint, quote=True),
        has_error="true" if view.has_error else "false",
        empty_message=html.escape(view.empty_state_message),
        empty_hidden="" if view.is_empty else " hidden",
        list_hidden=" hidden" if view.is_empty else "",
        cards=cards_html,
        feed_json=_feed_json(view),
    )


__all__ = [
    "DEFAULT_DECISIONS_ENDPOINT",
    "EMPTY_STATE_MESSAGE",
    "LOAD_ERROR_MESSAGE",
    "ControlView",
    "DecisionCardView",
    "DecisionsFeedView",
    "build_decisions_feed",
    "build_decisions_feed_from_result",
    "render_decisions_feed",
]
