"""Claiming a slot is conditional, so one half hour cannot be sold twice.

The bug this pins down: ``book_appointment`` read the slot, wrote the appointment,
then stamped the slot ``booked`` — without ever checking it was open. A second
booking of the same slot therefore succeeded. Both patients held an appointment on
the same half hour, the slot said ``booked`` either way, and nothing in the data
admitted there was a problem. The doctor would have discovered it when both arrived.

Checking the status in the calling tool would not have been enough. This agent
answers many calls at once — verified with fifty concurrent callers — and the same
slot is routinely offered to two of them. Between reading ``open`` and writing
``booked`` the other caller can do the same, and both succeed. So the transition has
to be conditional *in the store*, which on DynamoDB means a condition expression.

Run against both backends, because the in-memory fake is where the tests live and
DynamoDB is where the race actually happens.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

import boto3
import pytest
from moto import mock_aws

from clinic_front_desk.data_layer.dynamodb import DynamoAppointmentStore, create_table
from clinic_front_desk.data_layer.memory import MemoryAppointmentStore
from clinic_front_desk.models import Slot, SlotStatus, is_err

_REGION = "us-east-1"
_TABLE = "clinic-front-desk-claim-test"
_PROVIDER = "prov-raana"


def _slot(slot_id: str = "s1", status: SlotStatus = SlotStatus.OPEN) -> Slot:
    return Slot(
        id=slot_id,
        provider_id=_PROVIDER,
        service="ENT Consultation",
        start="2026-09-15T09:00:00Z",
        end="2026-09-15T09:30:00Z",
        status=status,
    )


@pytest.fixture
def memory_store() -> Any:
    return MemoryAppointmentStore()


@pytest.fixture
def dynamo_store() -> Iterator[Any]:
    with mock_aws():
        resource = boto3.resource("dynamodb", region_name=_REGION)
        table = create_table(resource, _TABLE)
        yield DynamoAppointmentStore(table)


@pytest.fixture(params=["memory", "dynamodb"])
def store(request: Any, memory_store: Any, dynamo_store: Any) -> Any:
    return memory_store if request.param == "memory" else dynamo_store


def test_claiming_an_open_slot_books_it(store: Any) -> None:
    store.add_slots([_slot()]).unwrap()

    claimed = store.claim_slot("s1")

    assert not is_err(claimed)
    assert claimed.value.status == SlotStatus.BOOKED
    assert store.get_slot("s1").unwrap().status == SlotStatus.BOOKED


def test_claiming_the_same_slot_twice_fails_the_second_time(store: Any) -> None:
    """The heart of it. On DynamoDB the second attempt is refused by the condition."""
    store.add_slots([_slot()]).unwrap()

    first = store.claim_slot("s1")
    second = store.claim_slot("s1")

    assert not is_err(first)
    assert is_err(second), "the slot was already booked"
    assert "not open" in second.error.detail.lower()
    # Still booked exactly once, by the winner.
    assert store.get_slot("s1").unwrap().status == SlotStatus.BOOKED


def test_a_blocked_slot_cannot_be_claimed(store: Any) -> None:
    """The doctor's lunch hour stays hers."""
    store.add_slots([_slot(status=SlotStatus.BLOCKED)]).unwrap()

    claimed = store.claim_slot("s1")

    assert is_err(claimed)
    assert store.get_slot("s1").unwrap().status == SlotStatus.BLOCKED


def test_claiming_a_missing_slot_is_not_found(store: Any) -> None:
    claimed = store.claim_slot("nope")

    assert is_err(claimed)
    assert claimed.error.kind == "not_found"


def test_a_claimed_slot_stops_being_offered(store: Any) -> None:
    """Availability must not keep offering a slot that has just been taken.

    On DynamoDB this is the GSI1 keys being regenerated by the write, moving the slot
    out of the open partition. Worth asserting: writing only the status attribute
    would leave it indexed as open and the agent would go on offering it.
    """
    store.add_slots([_slot()]).unwrap()
    before = store.list_open_slots(_PROVIDER, "ENT Consultation", "2026-09-01").unwrap()
    assert [s.id for s in before] == ["s1"]

    store.claim_slot("s1").unwrap()

    after = store.list_open_slots(_PROVIDER, "ENT Consultation", "2026-09-01").unwrap()
    assert [s.id for s in after] == []


def test_the_condition_is_enforced_by_dynamodb_not_only_by_the_read(
    dynamo_store: Any,
) -> None:
    """Prove the write itself is conditional, not just guarded by the prior read.

    The read-then-write version passes every test above while still being racy. This
    closes that gap: the slot is changed to ``booked`` behind the store's back, after
    it has read ``open``, which is exactly what a competing caller does. Only a real
    condition expression refuses.
    """
    dynamo_store.add_slots([_slot()]).unwrap()

    real_find = dynamo_store._find_by_entity_id
    stolen = {"done": False}

    def find_then_steal(entity: str, record_id: str) -> Any:
        item = real_find(entity, record_id)
        if entity == "Slot" and not stolen["done"]:
            stolen["done"] = True
            # Another caller wins the slot in the window after this read.
            dynamo_store.set_slot_status(record_id, SlotStatus.BOOKED).unwrap()
        return item

    dynamo_store._find_by_entity_id = find_then_steal  # type: ignore[method-assign]
    try:
        claimed = dynamo_store.claim_slot("s1")
    finally:
        dynamo_store._find_by_entity_id = real_find  # type: ignore[method-assign]

    assert stolen["done"], "the test did not actually simulate a competing booking"
    assert is_err(claimed), "the conditional write must refuse a slot taken mid-flight"
    assert "taken by another booking" in claimed.error.detail.lower()
